default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: promptly_development
  url: <%= ENV["DATABASE_URL"] %>

test:
  <<: *default
  database: promptly_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
